### ISSUE TITLE
大佬请教个奇怪的问题

### ISSUE THREAD

**Issue by goxofy** [Macfee/DingDing-Web#2]
两个钉钉帐号，一个能正常登录，也能获取到conversation，另外一个登录正常，获取conversation的时候出现错误了

报错内容如下

```
登陆成功
Traceback (most recent call last):
  File "/Users/MicroCat/Projects/DingDing-Web/dingding.py", line 258, in <module>
    cid_dict = ding.conversation()
  File "/Users/MicroCat/Projects/DingDing-Web/dingding.py", line 174, in conversation
    title = v['baseConversation']['title']
TypeError: string indices must be integers
```
然后我在代码174行加了 print(type(v))

发现能正常获取conversation的帐号这里输出类型是dict，不能获取的帐号这里输出类型是str

然后我在172行增加了 print(all_data)，发现输出是这样的
```
{'pipeline': 'sync', 'tooLong2Tag': 'center,legacy1', 'channel': 'sync', 'topic': 'sync', 'highPts': 1618494710627061, 'pts': 0, 'seq': 0, 'timestamp': 1618500745032}
```

不太理解这个，求助一下

**Comment by Macfee** [comment]
这个数据我没有做类型判断，dict类型的数据应该用get来做，这样会好点。你要看下前面获取的数据内容是什么。
